version: '3.9'
services:
  
  api:
    container_name: api
    environment:
      - "TZ=America/Sao_Paulo"
    build:
      context: ./api  # Diretório onde está o código do FastAPI
    ports:
      - "8000:8000"
    networks:
      my-network:
        ipv4_address: 172.20.0.10
    volumes:
      - ./api/:/app/
      - /var/log/log_api:/app/logs/
    environment:
      MYAPP_MODE: "development"
      MYAPP_MONGO_URI: "mongodb://your_username:mypass@mongodb:27017/"
      MYAPP_POSTGRES_URI: "postgresql://postgres:postgres@postgres:5432/"

    depends_on:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: mypass
    volumes:
      - mongodb_data:/data/db
    networks:
      my-network:
        ipv4_address: 172.20.0.2

  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
      - PORT=1234
    networks:
      my-network:
        ipv4_address: 172.20.0.5
    volumes:
      - adminmongo-data:/data

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      my-network:
        ipv4_address: 172.20.0.3
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your-email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "your-password"
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
    networks:
      my-network:
        ipv4_address: 172.20.0.4

networks:
  my-network:
    ipam:
        driver: default
        config:
          - subnet: 172.20.0.0/24

volumes:
  mongodb_data:
  postgres_data:
  pgadmin-data:
  adminmongo-data:
