"""initial

Revision ID: 0b08d7d11380
Revises: 
Create Date: 2024-05-20 03:00:44.593762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b08d7d11380'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftransacao',
    sa.Column('id_transacao', sa.Integer(), nullable=False),
    sa.Column('n_banco_pagador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_agencia_pagador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_conta_pagador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpfcnpj_pagador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chave_pix_pagador', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_banco_credor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_agencia_credor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('n_conta_credor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpfcnpj_credor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chave_pix_credor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valor_transacao', sa.Float(), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=False),
    sa.Column('id_status_transacao', sa.Integer(), nullable=False),
    sa.Column('id_tipo_transacao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_transacao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ftransacao')
    # ### end Alembic commands ###
